name: publish

on:
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        java: [ 21 ]
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew build
      - name: Merge Jars
        run: ./gradlew mergeJars
      - uses: BrycensRanch/read-properties-action@v1
        id: props
        with:
          file: gradle.properties
          all: true

      - name: Publish
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: ${{ steps.props.outputs.modrinth_id }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ steps.props.outputs.curseforge_id }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          files: |
            build/libs/merged/${{ steps.props.outputs.mod_id }}-${{ github.event.release.tag_name }}.jar

          name: ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}

          version-type: beta
          loaders: |
            fabric
            neoforge

          game-versions: ${{ steps.props.outputs.minecraft_version_range_fabric }}
          game-version-filter: releases

          dependencies: |
            cloth-config

          java: |
            21

          retry-attempts: 0
          fail-mode: skip

      - name: Upload assets to GitHub
        uses: AButler/upload-release-assets@v3.0
        with:
          files: "build/libs/merged/${{ steps.props.outputs.mod_id }}-${{ github.event.release.tag_name }}.jar;${{ steps.props.outputs.mod_id }}-fabric/build/libs/${{ steps.props.outputs.mod_id }}-fabric-${{ github.event.release.tag_name }}.jar;${{ steps.props.outputs.mod_id }}-fabric/build/libs/${{ steps.props.outputs.mod_id }}-fabric-${{ github.event.release.tag_name }}-sources.jar;${{ steps.props.outputs.mod_id }}-neoforge/build/libs/${{ steps.props.outputs.mod_id }}-neoforge-${{ github.event.release.tag_name }}.jar;${{ steps.props.outputs.mod_id }}-neoforge/build/libs/${{ steps.props.outputs.mod_id }}-neoforge-${{ github.event.release.tag_name }}-sources.jar"
          repo-token: ${{ secrets.GH_TOKEN }}

      - name: Hit mod update webhook
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.MOD_UPDATE_WEBHOOK }}
          method: 'GET'
          preventFailureOnNoResponse: 'true'
