name: publish-modrinth

on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Build artifacts
        run: ./gradlew build
      - uses: BrycensRanch/read-properties-action@v1
        id: gradle_props
        with:
          file: gradle.properties
          all: true
      - name: Publish fabric artifacts
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: CEvDfomf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            fabric/build/libs/winterly-fabric-${{ github.event.release.tag_name }}.jar
            fabric/build/libs/winterly-fabric-${{ github.event.release.tag_name }}-sources.jar
            
          name: Winterly Fabric ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}+fabric

          version-type: release
          loaders: |
            fabric
            quilt

          game-versions: ${{ steps.gradle_props.outputs.minecraft_version_range_fabric }}
          game-version-filter: releases
          
          dependencies: |
            fabric-api
            cloth-config
            trinkets

          java: |
            17

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip

      - name: Publish neoforge artifacts
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: CEvDfomf
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          files: |
            neoforge/build/libs/winterly-neoforge-${{ github.event.release.tag_name }}.jar
            neoforge/build/libs/winterly-neoforge-${{ github.event.release.tag_name }}-sources.jar

          name: Winterly NeoForge ${{ github.event.release.tag_name }}
          version: ${{ github.event.release.tag_name }}+neoforge

          version-type: alpha
          loaders: |
            neoforge

          game-versions: ${{ steps.gradle_props.outputs.minecraft_version_range_fabric }}
          game-version-filter: releases
          
          dependencies: |
            cloth-config
            curios

          java: |
            17

          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip